version: '3'

volumes:
  postgres_data:
  mongo_data:

services:

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak_db
      DB_USER: admin
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: e-tourist_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: [--auth]

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - "8082:8082"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo

#  backend:
#    container_name: backend
#    image: backend:1.0.0
#    build:
#      context: ../backend
#      dockerfile: ../backend/docker/Dockerfile
#    depends_on:
#      - mongo
#    environment:
#      - KEYCLOAK_AUTH_SERVER_URL=http://localhost:8080/auth/
#      - KEYCLOAK_CREDENTIALS_SECRET=VC7ZgWBbvmWgzH2QVW14ZZZ7TMeqDWys
#      - APP_TITLE=e-tourist
#      - APP_URL=http://localhost:8081
#      - MONGO_DB_CONN_STRING=mongodb://root:password@mongo:27017
#      - MONGO_DB_NAME=backend_db
#    ports:
#      - "8081:8081"

#  frontend:
#      container_name: frontend
#      image: frontend:1.0.0
#      build: ../frontend
#      ports:
#        - "4400:4400"
